# Flash programmer parameters file
# Automatically generated by SDK (09/06/2018 16:37:22).

set FLASH_FILE                    "/home/thekwan/Work/FPGA/ppc_linux_lcd3/SDK/SDK_Export/ppc_linux_lcd3_hw_platform/cache/simpleImage.virtex440-ml507-lcd3.elf.srec"
set FLASH_BASEADDR                0x8C000000
set FLASH_PROG_OFFSET             0x00000000
set FLASH_BUSWIDTH                16
set SCRATCH_BASEADDR              0x00000000
set SCRATCH_LEN                   0x10000000
set TARGET_TYPE                   "PPC440_VIRTEX5"
set PROC_INSTANCE                 "ppc440_0"
set EXTRA_COMPILER_FLAGS          "-mcpu=440"
set XMD_CONNECT                   "connect ppc hw  -debugdevice cpunr 1"
